### ISSUE TITLE
Standart Eloquent Model method with() do the same?

### ISSUE THREAD

**Issue by likemusic** [tjbp/eloquent-joins#2]
Standart Eloquent Model method with() do the same?
https://laravel.com/docs/5.1/eloquent-relationships#eager-loading

Therefor this package makes no sense? Or does it have any advantages?

**Comment by tjbp** [comment]
It's similar, but no, with() simply eager-loads the default functionality, which loads a collection of models with a matching foreign key for a relationship.

This package will perform a join, so that the relationship property will contain a single joined record from another table. This is primarily useful if you want to use the join to restrict theresults, not just select data from another table (the latter being possible with a simple relationship).
